/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
/** Analizador de expresiones aritmeticas sencillas. */
package Analizador;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENTERO = 2;
  /** RegularExpression Id. */
  int DECIMAL = 3;
  /** RegularExpression Id. */
  int TRUE = 4;
  /** RegularExpression Id. */
  int FALSE = 5;
  /** RegularExpression Id. */
  int CADENA = 6;
  /** RegularExpression Id. */
  int INT = 7;
  /** RegularExpression Id. */
  int DOUBLE = 8;
  /** RegularExpression Id. */
  int BOOLEAN = 9;
  /** RegularExpression Id. */
  int IMPRIMIR = 10;
  /** RegularExpression Id. */
  int MIENTRAS = 11;
  /** RegularExpression Id. */
  int FUNCION = 12;
  /** RegularExpression Id. */
  int RETORNO = 13;
  /** RegularExpression Id. */
  int BREAK = 14;
  /** RegularExpression Id. */
  int CONTINUE = 15;
  /** RegularExpression Id. */
  int SI = 16;
  /** RegularExpression Id. */
  int SINO = 17;
  /** RegularExpression Id. */
  int PCOMA = 18;
  /** RegularExpression Id. */
  int PARIZ = 19;
  /** RegularExpression Id. */
  int PARDE = 20;
  /** RegularExpression Id. */
  int CORI = 21;
  /** RegularExpression Id. */
  int CORD = 22;
  /** RegularExpression Id. */
  int LLAVE_I = 23;
  /** RegularExpression Id. */
  int LLAVE_D = 24;
  /** RegularExpression Id. */
  int MAS = 25;
  /** RegularExpression Id. */
  int MENOS = 26;
  /** RegularExpression Id. */
  int POR = 27;
  /** RegularExpression Id. */
  int DIV = 28;
  /** RegularExpression Id. */
  int IGUAL = 29;
  /** RegularExpression Id. */
  int MENORQUE = 30;
  /** RegularExpression Id. */
  int MAYORQUE = 31;
  /** RegularExpression Id. */
  int MENORIGUAL = 32;
  /** RegularExpression Id. */
  int MAYORIGUAL = 33;
  /** RegularExpression Id. */
  int IGUALACION = 34;
  /** RegularExpression Id. */
  int DIFERENCIACION = 35;
  /** RegularExpression Id. */
  int COMA = 36;
  /** RegularExpression Id. */
  int AND = 37;
  /** RegularExpression Id. */
  int OR = 38;
  /** RegularExpression Id. */
  int NOT = 39;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 40;
  /** RegularExpression Id. */
  int STRING = 49;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\\"\"",
    "<ENTERO>",
    "<DECIMAL>",
    "\"true\"",
    "\"false\"",
    "\"Cadena\"",
    "\"Int\"",
    "\"Double\"",
    "\"Boolean\"",
    "\"Imprimir\"",
    "\"Mientras\"",
    "\"Funcion\"",
    "\"Return\"",
    "\"Break\"",
    "\"continue\"",
    "\"if\"",
    "\"else\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\",\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "<IDENTIFICADOR>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 45>",
    "<token of kind 46>",
    "<token of kind 47>",
    "<token of kind 48>",
    "\"\\\"\"",
  };

}
